### ISSUE TITLE
High Level "Whole Environment" Grafana Dashboard

### ISSUE THREAD

**Issue by sguillen18** [logzio/microservices-demo#32]
After speaking with Vitac, some feedback we had is that there is no over arching, simplistic overview of our entire infrastructure in a single view.

We need something simple that incorporates both application and infrastructure level data that allows us to see holistically where a problem may lie and then drill down for deeper analysis.

**Comment by simfish85** [comment]
https://app.logz.io/#/dashboard/metrics/d/UIKfPEO7k/sock-shop-service-overview?orgId=5303&var-service=payment&switchToAccountId=302400

**Comment by sguillen18** [comment]
new dashboard is in the K8s folder of the metrics account.
